server:
  port: 8081
spring:
  datasource:
    password: Priyanka@7187
    url: jdbc:mysql://localhost:3306/miniproject
    username: root
    
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      keepalive-time: 100000
      
    
#JPA cfgs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
          
      